# -*- coding: utf-8 -*-
"""SWIGGY.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JXvPoVT0c3B4uilI6Gt1Na42BwYrMyJ5

#SWIGGY : DATA ANALYSIS USING PYTHON

#First Of All Import Libarires
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go

"""#Load The Data Set"""

df=pd.read_csv("/content/drive/MyDrive/DATASET/swiggy.csv")

"""#Display Basic Info"""

print(df.info())

print(df.head())

"""#Check For Missing Values"""

print(df.isnull().sum())

"""#Summary Statistics"""

print(df.describe())

"""#Set dark theme for plots

"""

plt.style.use('dark_background')

"""#Price Analysis

"""

plt.figure(figsize=(8,5))
sns.histplot(df['Price'], bins=30, kde=True, color='cyan')
plt.xlabel('Price')
plt.ylabel('Frequency')
plt.title('Price Distribution')
plt.show()

"""#🔹 Top Restaurants by Order Volume

"""

expensive_restaurants = df.groupby('Restaurant')['Price'].mean().sort_values(ascending=False).head(10)
plt.figure(figsize=(10,5))
sns.barplot(x=expensive_restaurants.values, y=expensive_restaurants.index, palette='magma')
plt.xlabel('Average Price')
plt.ylabel('Restaurant Name')
plt.title('Top 10 Expensive Restaurants')
plt.show()

"""# Rating Analysis"""

best_rated = df[df['Total ratings'] > 1000].nlargest(10, 'Avg ratings')
plt.figure(figsize=(10,5))
colors = sns.color_palette('viridis', len(best_rated))
plt.barh(best_rated['Restaurant'], best_rated['Avg ratings'], color=colors)
plt.xlabel('Average Rating')
plt.ylabel('Restaurant Name')
plt.title('Top 10 Best Rated Restaurants')
plt.gca().invert_yaxis()
plt.show()

"""# Correlation between ratings and price"""

plt.figure(figsize=(8,5))
sns.scatterplot(x=df['Price'], y=df['Avg ratings'], alpha=0.5, color='lime')
plt.xlabel('Price')
plt.ylabel('Average Rating')
plt.title('Price vs. Ratings')
plt.show()

"""#City & Area Trends

# Most active cities on Swiggy
"""

city_counts = df['City'].value_counts().head(10)
plt.figure(figsize=(10,5))
sns.barplot(x=city_counts.values, y=city_counts.index, palette='coolwarm')
plt.xlabel('Number of Restaurants')
plt.ylabel('City')
plt.title('Top 10 Cities with Most Restaurants')
plt.show()

"""# Delivery time analysis

"""

plt.figure(figsize=(8,5))
sns.histplot(df['Delivery time'], bins=20, kde=True, color='orange')
plt.xlabel('Delivery Time (minutes)')
plt.ylabel('Frequency')
plt.title('Distribution of Delivery Time')
plt.show()

"""#Food Type Insights

# Most popular food type
"""

food_counts = df['Food type'].value_counts().head(10)
plt.figure(figsize=(10,5))
sns.barplot(x=food_counts.values, y=food_counts.index, palette='plasma')
plt.xlabel('Number of Restaurants')
plt.ylabel('Food Type')
plt.title('Top 10 Most Common Food Types')
plt.show()

"""# Food type vs. Price

"""

food_price = df.groupby('Food type')['Price'].mean().sort_values(ascending=False).head(10)
plt.figure(figsize=(10,5))
sns.barplot(x=food_price.values, y=food_price.index, palette='rocket')
plt.xlabel('Average Price')
plt.ylabel('Food Type')
plt.title('Most Expensive Food Types')
plt.show()

"""# Food Type Distribution

"""

food_type_counts = df['Food type'].value_counts().head(6)
plt.figure(figsize=(8,8))
plt.pie(food_type_counts, labels=food_type_counts.index, autopct='%1.1f%%', startangle=140, colors=sns.color_palette('pastel'))
plt.title('Top Food Types Distribution')
plt.show()

"""#Heatmap: Correlation Matrix

"""

plt.figure(figsize=(10,6))
corr = df[['Price', 'Delivery time', 'Avg ratings', 'Total ratings']].corr()
sns.heatmap(corr, annot=True, cmap='coolwarm', linewidths=0.5)
plt.title('Correlation Matrix Heatmap')
plt.show()

"""#Average Delivery Time by City


"""

avg_delivery_time = df.groupby('City')['Delivery time'].mean().sort_values().head(10)
plt.figure(figsize=(10,6))
sns.barplot(x=avg_delivery_time.values, y=avg_delivery_time.index, palette='flare')
plt.xlabel('Average Delivery Time (min)')
plt.title('Cities with Quickest Deliveries')
plt.show()

"""#Most Common Price Points

"""

common_prices = df['Price'].value_counts().head(10)
plt.figure(figsize=(8, 6))
sns.barplot(x=common_prices.index, y=common_prices.values, palette='coolwarm')
plt.xlabel('Price')
plt.ylabel('Number of Restaurants')
plt.title('Top 10 Most Common Price Points')
plt.show()

"""#Average Delivery Time by Food Type

"""

avg_delivery_by_food_type = df.groupby('Food type')['Delivery time'].mean().sort_values(ascending=False).head(10)
plt.figure(figsize=(10, 6))
sns.barplot(x=avg_delivery_by_food_type.values, y=avg_delivery_by_food_type.index, palette='YlOrBr')
plt.xlabel('Average Delivery Time (minutes)')
plt.ylabel('Food Type')
plt.title('Top 10 Food Types by Average Delivery Time')
plt.show()